# Configuration for document splitting pipeline

DocumentSplitter:
  # Basic settings
  max_filename_length: 50
  max_sections: 100
  
  # Section boundaries  
  overlap_pages: 0

  top_margin_px: 10
  top_threshold_percent: 20  # If Y < 15% page height, start from top
