version: '3.8'

services:
  luigi-scheduler:
    image: python:3.13-slim
    ports:
      - "8082:8082"
    volumes:
      - .:/app
      - ./luigi_pipeline/temp:/luigi/state
    working_dir: /app
    command: >
      sh -c "pip install poetry && 
             poetry install && 
             poetry run luigid --port 8082 --state-path /luigi/state/luigi-state.pickle"
    environment:
      - PYTHONPATH=/app

  luigi-worker:
    image: python:3.13-slim  
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - luigi-scheduler
    environment:
      - PYTHONPATH=/app
    command: >
      sh -c "pip install poetry && 
             poetry install && 
             poetry run python -m luigi 
             --module luigi_pipeline.tasks.hello_task HelloTask 
             --scheduler-host luigi-scheduler"