# Existing config...
StructureDetector:
  min_block_area: 100
  zoom_factor: 1.0
  merge_gap_px: 5
  max_pages: 1000

# DODAJ TO:
SemanticStructureDetector:
  max_pages: 1000
  min_section_pages: 1
  header_confidence_threshold: 0.7
  toc_detection_enabled: true
  extract_page_numbers: true

StructureSplitter:
  min_section_height_px: 10
  max_filename_length: 50
  output_format: "pdf"